name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linkerd2:
    strategy:
      matrix:
        version: 
          - arm-2.7.1

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: gazzyt/linkerd2
        ref: ${{ matrix.version }}
    - name: Build and push scope image
      run: |
          docker buildx build \
            --platform linux/arm/v7 \
            --output "type=image,push=true" \
            --build-arg IMAGE_TAG=${{ matrix.version }} \
            -t ${{ secrets.registryUsername }}/linkerd2-proxy:${{ matrix.version }} .

  linkerd2-proxy-init:
    strategy:
      matrix:
        version: 
          - arm-1.3.2

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: gazzyt/linkerd2-proxy-init
        ref: ${{ matrix.version }}
    - name: Build and push scope image
      run: |
          docker buildx build \
            --platform linux/arm/v7 \
            --output "type=image,push=true" \
            --build-arg IMAGE_TAG=${{ matrix.version }} \
            -t ${{ secrets.registryUsername }}/linkerd2-proxy-init:${{ matrix.version }} .

  linkerd2-proxy:
    strategy:
      matrix:
        version: 
          - arm-2.7.0

    runs-on: ubuntu-latest
         
    steps:
    - uses: actions/checkout@v2
      with:
        repository: gazzyt/linkerd2-proxy
        ref: ${{ matrix.version }}
    - name: Build and push scope image
      run: |
          docker buildx build \
            --platform linux/arm/v7 \
            --output "type=image,push=true" \
            --build-arg IMAGE_TAG=${{ matrix.version }} \
            -t ${{ secrets.registryUsername }}/linkerd2-proxy:${{ matrix.version }} .
